[application]
name = "airport-app-frontend"

[web.app]
# HTML title tag content
title = "SkyBook - Find Your Next Adventure"
base_path = "/"

[web.resource]
# CSS global y variables
style = ["assets/main.css"]
script = []

[web.resource.dev]
# Archivos JS solo en desarrollo (si los necesitas)
script = []



